# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEUjEanXKgZD7WNVVr3omjqcdO0ctTkD
"""

# Use seaborn for pairplot.
!pip install -q seaborn

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Make NumPy printouts easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

print(tf.__version__)

train = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQGCLRmqXnwOk43CcaiNVaunKBK-lq2V3FHWl95XTQoQcmdKfF_GV_vWFMTeI9ddJUC7aMM4inHZlOk/pub?gid=1967933179&single=true&output=csv'

column_names = ['loan_id','no_of_dependents','education','self_employed','income_annum', 'loan_amount', 'loan_term', 'cibil_score',
                'residential_assets_value','commercial_assets_value', 'luxury_assets_value','bank_asset_value','loan_status']

raw_dataset_train = pd.read_csv(train, names=column_names, header=0,
                          na_values='?', comment='\t',
                          sep=',', # Changed separator to ','
                          skipinitialspace=True)

dataset = raw_dataset_train.copy()
dataset.tail()

dataset.dropna()
dataset.tail()

for row in dataset['loan_status']:
    if row == 'Approved':
        dataset['loan_status'] = dataset['loan_status'].replace(row, 1)
    elif row == 'Rejected':
        dataset['loan_status'] = dataset['loan_status'].replace(row, 0)

for row in dataset['education']:
    if row == 'Graduate':
        dataset['education'] = dataset['education'].replace(row, 1)
    elif row == 'Not Graduate':
        dataset['education'] = dataset['education'].replace(row, 0)

for row in dataset['self_employed']:
    if row == 'Yes':
        dataset['self_employed'] = dataset['self_employed'].replace(row, 1)
    elif row == 'No':
        dataset['self_employed'] = dataset['self_employed'].replace(row, 0)

test = dataset.pop('loan_id')

dataset['no_of_dependents'] = dataset['no_of_dependents'].astype(int)
dataset['education'] = dataset['education'].astype(int)
dataset['self_employed'] = dataset['self_employed'].astype(int)
dataset['loan_amount'] = dataset['loan_amount'].astype(int)
dataset['loan_term'] = dataset['loan_term'].astype(int)
dataset['cibil_score'] = dataset['cibil_score'].astype(int)
dataset['residential_assets_value'] = dataset['residential_assets_value'].astype(int)
dataset['commercial_assets_value'] = dataset['commercial_assets_value'].astype(int)
dataset['luxury_assets_value'] = dataset['luxury_assets_value'].astype(int)
dataset['bank_asset_value'] = dataset['bank_asset_value'].astype(int)
dataset['loan_status'] = dataset['loan_status'].astype(int)

dataset.tail()
